FROM dregistry.lyft.net/python:latest
RUN apt-get update -y && \
    apt-get install -y build-essential autoconf libtool && \
    pip install jinja2==2.8 pyyaml
RUN apt-get install -y gettext
#RUN cd /build/source/conf && \
#    python generate.py && \
#    mkdir -p /build/conf && \
#    mv development.yaml /build/conf/development.yaml && \
#    ls -la /build/conf
