FROM dregistry.lyft.net/base:latest
RUN apt-get update -y && \
    apt-get install -y build-essential autoconf libtool
ADD source /build/source
RUN cd /build/source && \
    autoreconf -fvi && \
    ./configure && \
    make && \
    make install && \
    mv /usr/local/sbin/nutcracker /build/nutcracker
