#!/bin/bash
set -e
# libtoolize does not work across bind mounts in devbox
mkdir -p /build/source/generated
cd /build/source/conf && python generate.py
if [ -f /build/source/nutcracker ]; then
  echo "Already built"
  exit 0
fi
cd /build
cp -R source source2
cd source2
autoreconf -fvi
./configure
make
make install
mv /usr/local/sbin/nutcracker /build/source/nutcracker
